// Code generated by "stringer -type=Suit,Rank"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Bastoni-1]
	_ = x[Coppe-2]
	_ = x[Denari-3]
	_ = x[Spade-4]
}

const _Suit_name = "BastoniCoppeDenariSpade"

var _Suit_index = [...]uint8{0, 7, 12, 18, 23}

func (i Suit) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Suit_index)-1 {
		return "Suit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Suit_name[_Suit_index[idx]:_Suit_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Asso-1]
	_ = x[Due-2]
	_ = x[Tre-3]
	_ = x[Quattro-4]
	_ = x[Cinque-5]
	_ = x[Sei-6]
	_ = x[Sette-7]
	_ = x[Fante-8]
	_ = x[Cavallo-9]
	_ = x[Re-10]
}

const _Rank_name = "AssoDueTreQuattroCinqueSeiSetteFanteCavalloRe"

var _Rank_index = [...]uint8{0, 4, 7, 10, 17, 23, 26, 31, 36, 43, 45}

func (i Rank) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Rank_index)-1 {
		return "Rank(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rank_name[_Rank_index[idx]:_Rank_index[idx+1]]
}
