// Code generated by "stringer -type=Suit,Rank"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Clubs-1]
	_ = x[Cups-2]
	_ = x[Coins-3]
	_ = x[Swords-4]
}

const _Suit_name = "BastoniCoppeDenariSpade"

var _Suit_index = [...]uint8{0, 7, 12, 18, 23}

func (i Suit) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Suit_index)-1 {
		return "Suit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Suit_name[_Suit_index[idx]:_Suit_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ace-1]
	_ = x[Two-2]
	_ = x[Three-3]
	_ = x[Four-4]
	_ = x[Five-5]
	_ = x[Six-6]
	_ = x[Seven-7]
	_ = x[Jack-8]
	_ = x[Knight-9]
	_ = x[King-10]
}

const _Rank_name = "AssoDueTreQuattroCinqueSeiSetteFanteCavalloRe"

var _Rank_index = [...]uint8{0, 4, 7, 10, 17, 23, 26, 31, 36, 43, 45}

func (i Rank) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Rank_index)-1 {
		return "Rank(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rank_name[_Rank_index[idx]:_Rank_index[idx+1]]
}
