apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yml
  - etcd-cluster.yaml
  - marafonet-deployment.yaml
  - matchmaking-deployment.yaml
  - marafonet-hpa.yaml
  - marafonet-service.yml